import { useState, useEffect } from "react";

type Language = "en" | "pt";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

// Simple translations
const translations = {
  en: {
    "login.title": "Sign In",
    "login.email": "Email",
    "login.password": "Password",
    "login.remember": "Remember me",
    "login.forgot": "Forgot password?",
    "login.signin": "Sign In",
    "login.signup": "Don't have an account?",
    "login.signingIn": "Signing in...",
    "login.forgotPassword": "Forgot password?",
    "login.signUpHere": "Sign up here",
    "login.dashboardTitle": "Hospital Sustainability Dashboard",
    "login.dashboardDesc":
      "Manage and monitor sustainability metrics across all hospital departments",
    "login.enterCredentials": "Enter your email and password to sign in!",
    "signup.title": "Create Account",
    "signup.name": "Full Name",
    "signup.confirmPassword": "Confirm Password",
    "signup.create": "Create Account",
    "signup.login": "Already have an account?",
    "signup.creating": "Creating account...",
    "signup.backToLogin": "Back to login",
    "signup.role": "Role",
    "signup.hospital": "Hospital",
    "signup.selectRole": "Select a role",
    "signup.selectHospital": "Select a hospital",
    "signup.admin": "Admin",
    "signup.departmentHead": "Department Head",
    "signup.accountCreated": "Account created successfully!",
    "signup.redirecting": "Redirecting to login...",
    "dashboard.admin": "Admin Dashboard",
    "dashboard.department": "Department Dashboard",
    "dashboard.manage": "Manage hospital sustainability metrics and reports",
    "dashboard.metrics":
      "Manage your hospital's monthly sustainability metrics",
    "menu.dashboard": "Dashboard",
    "menu.dataAnalysis": "Data Analysis",
    "menu.fileUpload": "File Upload",
    "menu.notifications": "Notifications",
    "menu.dataEntry": "Data Entry",
    "menu.reports": "Reports",
    "menu.export": "Export Data",
    "menu.settings": "Settings",
    "menu.supportMessages": "Support Messages",
    "menu.contact": "Contact",
    "menu.help": "Help",
    "menu.hospitalVariables": "Hospital Variables",
    "menu.hospitalForms": "Hospital Forms",
    "others.menu": "Others",
    "back.to.main": "Back to Main Site",
    "user.menu": "User Menu",
    logout: "Logout",
    menu: "Menu",
    others: "Others",
    // Common
    "common.loading": "Loading...",
    "common.loadingData": "Loading data...",
    "common.loadingForm": "Loading form...",
    "common.loadingDashboard": "Loading dashboard...",
    "common.noHospitals": "No hospitals available",
    "common.tryAgain": "Try Again",
    "common.current": "Current",
    "common.average": "Average",
    "common.peak": "Peak",
    "common.never": "Never",
    "common.notSubmitted": "Not submitted",
    "buttons.view": "View",
    "buttons.edit": "Edit",
    "buttons.saveChanges": "Save Changes",
    "buttons.changePassword": "Change Password",
    "buttons.configure": "Configure",
    "buttons.markAllRead": "Mark all as read",
    "buttons.markAsRead": "Mark as read",
    "buttons.goToDataEntry": "Go to Data Entry",
    // Department - Dashboard
    "dept.dashboard.dataEntryReports": "Data Entry & Reports",
    "dept.dashboard.enterMonthly": "Enter monthly metrics and view reports",
    "dept.dashboard.metricsSubmitted": "Metrics Submitted",
    "dept.dashboard.submissionPending": "Submission Pending",
    "dept.dashboard.submitNow": "Click here to submit now",
    "dept.dashboard.energyTrendTitle": "12-Month Energy Trend",
    "dept.dashboard.energyTrendDesc":
      "Your hospital's energy usage over the past year",
    "dept.dashboard.totalEntries": "Total Entries",
    "dept.dashboard.entriesSubtitle": "Monthly reports submitted",
    "dept.dashboard.avgEnergy": "Average Energy Usage",
    "dept.dashboard.monthlyAverage": "Monthly average",
    "dept.dashboard.lastUpdated": "Last Updated",
    "dept.dashboard.lastDataEntry": "Last data entry",
    // Department - Data Entry
    "dept.dataEntry.title": "Data Entry & Reports",
    "dept.dataEntry.subtitle":
      "Manage your monthly sustainability data and view reports",
    "dept.dataEntry.tab.entry": "Data Entry",
    "dept.dataEntry.tab.reports": "Reports & Analytics",
    "dept.dataEntry.table.formName": "Form Name",
    "dept.dataEntry.table.status": "Status",
    "dept.dataEntry.table.submittedDate": "Submitted Date",
    "dept.dataEntry.table.actions": "Actions",
    "dept.dataEntry.status.submitted": "Submitted",
    "dept.dataEntry.status.draft": "Draft",
    "dept.dataEntry.button.view": "View",
    "dept.dataEntry.button.edit": "Edit",
    "dept.reports.monthlyReport": "Monthly Report",
    "dept.reports.status": "Status",
    "dept.reports.period": "Period",
    "dept.reports.submitted": "Submitted",
    // Department - Reports & Analytics
    "dept.reports.energyTrendTitle": "12-Month Energy Trend",
    "dept.reports.energyTrendDesc":
      "Your hospital's energy usage over the past year",
    "dept.reports.co2TrendTitle": "12-Month CO₂ Emissions Trend",
    "dept.reports.co2TrendDesc":
      "Your hospital's CO₂ emissions over the past year",
    "dept.reports.trendAnalysis": "Trend Analysis",
    "dept.reports.energyTrend": "Energy Trend",
    "dept.reports.waterTrend": "Water Trend",
    "dept.reports.co2Trend": "CO₂ Trend",
    "dept.reports.wasteTrend": "Waste Trend",
    "dept.reports.improving": "Improving",
    "dept.reports.needsAttention": "Needs attention",
    "dept.reports.co2Emissions": "CO₂ Emissions",
    "dept.reports.currentMonth": "Current Month",
    "dept.reports.monthlyAverage": "Monthly Average",
    "dept.reports.yearTotal": "Year Total",
    "dept.reports.upcoming": "Upcoming",
    "dept.reports.nextReport": "Next Report",
    "dept.reports.dueSoon": "Due Soon",
    "dept.reports.dueDate": "Due Date",
    "dept.reports.daysLeft": "Days Left",
    "dept.reports.startReport": "Start Report",
    "dept.reports.download": "Download",
    "dept.reports.viewDetails": "View Details",
    "dept.reports.completed": "Completed",
    "dept.reports.notSubmitted": "Not submitted",
    // Department - Notifications
    "dept.notifications.title": "Notifications",
    "dept.notifications.subtitle":
      "Stay updated with important messages and alerts",
    "dept.notifications.unread": "unread",
    "dept.notifications.loading": "Loading notifications…",
    "dept.notifications.failed": "Failed to load notifications",
    "dept.notifications.none": "No notifications",
    "dept.notifications.caughtUp":
      "You're all caught up! Check back later for new updates.",
    "dept.notifications.new": "New",
    "dept.notifications.settings": "Notification Settings",
    "dept.notifications.managePrefs": "Manage your notification preferences",
    "dept.notifications.email": "Email Notifications",
    "dept.notifications.emailDesc": "Receive notifications via email",
    "dept.notifications.reminders": "Report Reminders",
    "dept.notifications.remindersDesc":
      "Get reminded about upcoming report deadlines",
    "dept.notifications.system": "System Updates",
    "dept.notifications.systemDesc":
      "Receive notifications about system maintenance and updates",
    // Department - Settings
    "dept.settings.title": "Settings",
    "dept.settings.subtitle": "Manage your account settings and preferences",
    "dept.settings.profile": "Profile Settings",
    "dept.settings.fullName": "Full Name",
    "dept.settings.hospital": "Hospital",
    "dept.settings.department": "Department",
    "dept.settings.notifications": "Notification Settings",
    "dept.settings.emailNotifications": "Email Notifications",
    "dept.settings.reportReminders": "Report Reminders",
    "dept.settings.dataUpdates": "Data Updates",
    "dept.settings.dataUpdatesDesc": "Notifications when data is updated",
    "dept.settings.security": "Security Settings",
    "dept.settings.currentPassword": "Current Password",
    "dept.settings.newPassword": "New Password",
    "dept.settings.confirmPassword": "Confirm New Password",
    "dept.settings.system": "System Settings",
    "dept.settings.autoSaveDrafts": "Auto-save Drafts",
    "dept.settings.autoSaveDraftsDesc":
      "Automatically save form data as drafts",
    "dept.settings.dataExport": "Data Export",
    "dept.settings.dataExportDesc": "Allow data export functionality",
    "dept.settings.analytics": "Analytics",
    "dept.settings.analyticsDesc": "Enable analytics and reporting features",
    // Department - Help
    "dept.help.title": "Help & Support",
    "dept.help.subtitle": "Get help with using the sustainability dashboard",
    "dept.help.sendMessage": "Send Message",
    "dept.help.firstName": "First Name",
    "dept.help.lastName": "Last Name",
    "dept.help.phoneNumber": "Phone Number",
    "dept.help.message": "Message",
    "dept.help.sending": "Sending...",
    "dept.help.send": "Send Message",
    "dept.help.contactInfo": "Contact Information",
    "dept.help.phone": "Phone",
    "dept.help.email": "Email",
    "dept.help.address": "Address",
    "dept.help.directSupport": "Direct Support",
    "dept.help.chatWhatsApp": "Chat on WhatsApp",
    "dept.help.chatWhatsAppDesc": "Message our team on WhatsApp",
    // Admin - Common/Sections
    "admin.common.loading": "Loading...",
    "admin.common.loadingUsers": "Loading users...",
    "admin.common.loadingDepartments": "Loading department heads...",
    "admin.common.noDepartments": "No department heads found",
    "admin.common.noForms": "No forms data found",
    "admin.common.notAssigned": "Not assigned",
    "admin.common.na": "N/A",
    "admin.common.never": "Never",
    "admin.common.submitted": "Submitted",
    "admin.common.pending": "Pending",
    "admin.dashboard.deptSectionTitle":
      "Department Heads - Submission Status & Reminders",
    "admin.dashboard.deptSectionHelp":
      "Assign department heads to hospitals in the User Management section below to enable reminder functionality.",
    "admin.dashboard.sendReminder": "Send Reminder",
    "admin.dashboard.sending": "Sending...",
    "admin.dashboard.submitted": "Submitted",
    "admin.users.sectionTitle": "User Management - Hospital Assignment",
    "admin.users.loading": "Loading users...",
    "admin.users.allAssigned": "All users have been assigned to hospitals!",
    "admin.users.table.name": "Name",
    "admin.users.table.email": "Email",
    "admin.users.table.role": "Role",
    "admin.users.table.created": "Created",
    "admin.users.table.assignHospital": "Assign Hospital",
    "admin.forms.sectionTitle": "All Hospital Submissions - Forms Data",
    "admin.forms.sectionDesc":
      'View all form submissions from every hospital. Click "View Report" to see detailed metrics.',
    "admin.forms.loading": "Loading forms data...",
    "admin.forms.error": "Error loading forms data",
    "admin.forms.totals": "Total Forms",
    "admin.forms.submitted": "Submitted",
    "admin.forms.pending": "Pending",
    "admin.forms.refresh": "Refresh",
    "admin.forms.table.hospital": "Hospital",
    "admin.forms.table.deptHead": "Department Head",
    "admin.forms.table.monthYear": "Month/Year",
    "admin.forms.table.status": "Status",
    "admin.forms.table.submittedAt": "Submitted At",
    "admin.forms.table.created": "Created",
    "admin.forms.table.actions": "Actions",
    "admin.forms.viewReport": "View Report",
    // Hospital Forms Management translations
    "admin.hospitalForms.title": "Hospital Forms Management",
    "admin.hospitalForms.description":
      "Manage and fill out forms for all hospitals",
    "admin.hospitalForms.filters": "Filters",
    "admin.hospitalForms.selectHospital": "Select Hospital",
    "admin.hospitalForms.allHospitals": "All Hospitals",
    "admin.hospitalForms.currentMonth": "Current Month",
    "admin.hospitalForms.currentYear": "Current Year",
    "admin.hospitalForms.refresh": "Refresh",
    "admin.hospitalForms.hospitalForms": "Hospital Forms",
    "admin.hospitalForms.loading": "Loading forms...",
    "admin.hospitalForms.noForms": "No forms found for the selected criteria",
    "admin.hospitalForms.createNew": "Create New Form",
    "admin.hospitalForms.hospital": "Hospital",
    "admin.hospitalForms.monthYear": "Month/Year",
    "admin.hospitalForms.status": "Status",
    "admin.hospitalForms.submittedAt": "Submitted At",
    "admin.hospitalForms.lastUpdated": "Last Updated",
    "admin.hospitalForms.actions": "Actions",
    "admin.hospitalForms.view": "View",
    "admin.hospitalForms.edit": "Edit",
    "admin.hospitalForms.submitted": "Submitted",
    "admin.hospitalForms.pending": "Pending",
    "admin.hospitalForms.notSubmitted": "Not submitted",
    "admin.hospitalForms.backToForms": "Back to Hospital Forms",
    "admin.hospitalForms.viewMode":
      "View Mode: This form has been submitted and is read-only",
    // New sustainability metrics translations
    "metrics.kilometersTravelled": "Kilometers Travelled",
    "metrics.kilometersByFuel": "Kilometers by Fuel",
    "metrics.renewableEnergyCreated": "Renewable Energy Created",
    "metrics.licensePlatesRecorded": "License Plates Recorded",
    "metrics.totalKilometers": "Total Kilometers",
    "metrics.gasKilometers": "Gas Kilometers",
    "metrics.dieselKilometers": "Diesel Kilometers",
    "metrics.gasolineKilometers": "Gasoline Kilometers",
    "metrics.energyUsage": "Energy Usage",
    "metrics.waterUsage": "Water Usage",
    "metrics.wasteGenerated": "Waste Generated",
    "metrics.co2Emissions": "CO₂ Emissions",
    "metrics.renewableEnergyRatio": "Renewable Energy Ratio",
    "metrics.renewableVsTotal": "Renewable vs Total Energy",
    "metrics.licensePlateNumber": "License Plate Number",
    "metrics.vehicleIdentifier": "Vehicle license plate identifier",
    "metrics.kilometersGas": "Kilometers travelled by vehicles using gas",
    "metrics.kilometersDiesel": "Kilometers travelled by vehicles using diesel",
    "metrics.kilometersGasoline":
      "Kilometers travelled by vehicles using gasoline",
    "metrics.renewableEnergyOnSite":
      "Amount of renewable energy generated on-site",
    "metrics.sumAcrossDepartments": "Sum across all departments for this month",
    "metrics.totalEntriesWithPlates":
      "Total entries with plate numbers this month",
    "metrics.energyTrend": "Energy Trend",
    "metrics.energyTrendDesc":
      "Your hospital's energy usage over the past year",
    "metrics.energyEfficiency": "Energy Efficiency",
    "metrics.energy": "Energy",
    "metrics.energyUsageData": "Energy Usage Data",
    "metrics.energyTrendTitle": "12-Month Energy Trend",
    "metrics.energyTrendDescription":
      "Your hospital's energy usage over the past year",
    "metrics.energyUsageKwh": "Energy Usage (kWh)",
    "metrics.waterUsageM3": "Water Usage (m³)",
    "metrics.wasteType1": "Type 1 Waste (kg)",
    "metrics.wasteType2": "Type 2 Waste (kg)",
    "metrics.wasteType3": "Type 3 Waste (kg)",
    "metrics.wasteType4": "Type 4 Waste (kg)",
    "metrics.co2EmissionsKg": "CO₂ Emissions (kg CO₂e)",
    "metrics.kilometersGasKm": "Kilometers (Gas) (km)",
    "metrics.litersGasConsumed": "Liters Consumed (Gas)",
    "metrics.litersGasUsed": "Liters of gas consumed by vehicles",
    "metrics.kilometersDieselKm": "Kilometers (Diesel) (km)",
    "metrics.litersDieselConsumed": "Liters Consumed (Diesel)",
    "metrics.litersDieselUsed": "Liters of diesel consumed by vehicles",
    "metrics.kilometersGasolineKm": "Kilometers (Gasoline) (km)",
    "metrics.litersGasolineConsumed": "Liters Consumed (Gasoline)",
    "metrics.litersGasolineUsed": "Liters of gasoline consumed by vehicles",
    "metrics.licensePlate": "License Plate",
    "metrics.renewableEnergyCreatedKwh": "Renewable Energy Created (kWh)",
  },
  pt: {
    "login.title": "Entrar",
    "login.email": "Email",
    "login.password": "Senha",
    "login.remember": "Lembrar de mim",
    "login.forgot": "Esqueceu a senha?",
    "login.signin": "Entrar",
    "login.signup": "Não tem conta?",
    "login.signingIn": "A entrar...",
    "login.forgotPassword": "Esqueceu a senha?",
    "login.signUpHere": "Registar aqui",
    "login.dashboardTitle": "Painel de Sustentabilidade Hospitalar",
    "login.dashboardDesc":
      "Gerir e monitorizar métricas de sustentabilidade em todos os departamentos hospitalares",
    "login.enterCredentials":
      "Introduza o seu email e palavra-passe para entrar!",
    "signup.title": "Criar Conta",
    "signup.name": "Nome Completo",
    "signup.confirmPassword": "Confirmar Senha",
    "signup.create": "Criar Conta",
    "signup.login": "Já tem conta?",
    "signup.creating": "A criar conta...",
    "signup.backToLogin": "Voltar ao login",
    "signup.role": "Função",
    "signup.hospital": "Hospital",
    "signup.selectRole": "Selecionar uma função",
    "signup.selectHospital": "Selecionar um hospital",
    "signup.admin": "Administrador",
    "signup.departmentHead": "Responsável de Departamento",
    "signup.accountCreated": "Conta criada com sucesso!",
    "signup.redirecting": "A redirecionar para o login...",
    "dashboard.admin": "Painel Administrativo",
    "dashboard.department": "Painel do Departamento",
    "dashboard.manage":
      "Gerencie métricas de sustentabilidade hospitalar e relatórios",
    "dashboard.metrics":
      "Gerencie as métricas mensais de sustentabilidade do seu hospital",
    "menu.dashboard": "Painel",
    "menu.dataAnalysis": "Análise de Dados",
    "menu.fileUpload": "Upload de Arquivos",
    "menu.notifications": "Notificações",
    "menu.dataEntry": "Entrada de Dados",
    "menu.reports": "Relatórios",
    "menu.export": "Exportar Dados",
    "menu.settings": "Configurações",
    "menu.supportMessages": "Mensagens de Suporte",
    "menu.contact": "Contato",
    "menu.help": "Ajuda",
    "menu.hospitalVariables": "Variáveis do Hospital",
    "menu.hospitalForms": "Formulários do Hospital",
    "others.menu": "Outros",
    "back.to.main": "Voltar ao Site Principal",
    "user.menu": "Menu do Usuário",
    logout: "Sair",
    menu: "Menu",
    others: "Outros",
    // Common
    "common.loading": "A carregar...",
    "common.loadingData": "A carregar dados...",
    "common.loadingForm": "A carregar formulário...",
    "common.loadingDashboard": "A carregar painel...",
    "common.noHospitals": "Nenhum hospital disponível",
    "common.tryAgain": "Tentar novamente",
    "common.current": "Atual",
    "common.average": "Média",
    "common.peak": "Pico",
    "common.never": "Nunca",
    "common.notSubmitted": "Não submetido",
    "buttons.view": "Ver",
    "buttons.edit": "Editar",
    "buttons.saveChanges": "Guardar Alterações",
    "buttons.changePassword": "Alterar Palavra-passe",
    "buttons.configure": "Configurar",
    "buttons.markAllRead": "Marcar tudo como lido",
    "buttons.markAsRead": "Marcar como lido",
    "buttons.goToDataEntry": "Ir para Entrada de Dados",
    // Department - Dashboard
    "dept.dashboard.dataEntryReports": "Entrada de Dados e Relatórios",
    "dept.dashboard.enterMonthly":
      "Introduza métricas mensais e veja relatórios",
    "dept.dashboard.metricsSubmitted": "Métricas Submetidas",
    "dept.dashboard.submissionPending": "Submissão Pendente",
    "dept.dashboard.submitNow": "Clique aqui para submeter agora",
    "dept.dashboard.energyTrendTitle": "Tendência de Energia (12 meses)",
    "dept.dashboard.energyTrendDesc":
      "Consumo de energia do seu hospital no último ano",
    "dept.dashboard.totalEntries": "Entradas Totais",
    "dept.dashboard.entriesSubtitle": "Relatórios mensais submetidos",
    "dept.dashboard.avgEnergy": "Consumo Médio de Energia",
    "dept.dashboard.monthlyAverage": "Média mensal",
    "dept.dashboard.lastUpdated": "Última Atualização",
    "dept.dashboard.lastDataEntry": "Última entrada de dados",
    // Department - Data Entry
    "dept.dataEntry.title": "Entrada de Dados e Relatórios",
    "dept.dataEntry.subtitle":
      "Gira os seus dados mensais de sustentabilidade e veja relatórios",
    "dept.dataEntry.tab.entry": "Entrada de Dados",
    "dept.dataEntry.tab.reports": "Relatórios e Análises",
    "dept.dataEntry.table.formName": "Nome do Formulário",
    "dept.dataEntry.table.status": "Estado",
    "dept.dataEntry.table.submittedDate": "Data de Submissão",
    "dept.dataEntry.table.actions": "Ações",
    "dept.dataEntry.status.submitted": "Submetido",
    "dept.dataEntry.status.draft": "Rascunho",
    "dept.dataEntry.button.view": "Ver",
    "dept.dataEntry.button.edit": "Editar",
    "dept.reports.monthlyReport": "Relatório Mensal",
    "dept.reports.status": "Estado",
    "dept.reports.period": "Período",
    "dept.reports.submitted": "Submetido",
    // Department - Reports & Analytics
    "dept.reports.energyTrendTitle": "Tendência de Energia (12 meses)",
    "dept.reports.energyTrendDesc":
      "Consumo de energia do seu hospital no último ano",
    "dept.reports.co2TrendTitle": "Tendência de Emissões CO₂ (12 meses)",
    "dept.reports.co2TrendDesc":
      "Emissões de CO₂ do seu hospital no último ano",
    "dept.reports.trendAnalysis": "Análise de Tendências",
    "dept.reports.energyTrend": "Tendência de Energia",
    "dept.reports.waterTrend": "Tendência de Água",
    "dept.reports.co2Trend": "Tendência de CO₂",
    "dept.reports.wasteTrend": "Tendência de Resíduos",
    "dept.reports.improving": "A melhorar",
    "dept.reports.needsAttention": "Precisa de atenção",
    "dept.reports.co2Emissions": "Emissões de CO₂",
    "dept.reports.currentMonth": "Mês Atual",
    "dept.reports.monthlyAverage": "Média Mensal",
    "dept.reports.yearTotal": "Total Anual",
    "dept.reports.upcoming": "Próximos",
    "dept.reports.nextReport": "Próximo Relatório",
    "dept.reports.dueSoon": "Vence Brevemente",
    "dept.reports.dueDate": "Data de Vencimento",
    "dept.reports.daysLeft": "Dias Restantes",
    "dept.reports.startReport": "Iniciar Relatório",
    "dept.reports.download": "Descarregar",
    "dept.reports.viewDetails": "Ver Detalhes",
    "dept.reports.completed": "Concluído",
    "dept.reports.notSubmitted": "Não submetido",
    // Department - Notifications
    "dept.notifications.title": "Notificações",
    "dept.notifications.subtitle":
      "Mantenha-se atualizado com mensagens e alertas importantes",
    "dept.notifications.unread": "por ler",
    "dept.notifications.loading": "A carregar notificações…",
    "dept.notifications.failed": "Falha ao carregar as notificações",
    "dept.notifications.none": "Sem notificações",
    "dept.notifications.caughtUp":
      "Está a par de tudo! Volte mais tarde para novas atualizações.",
    "dept.notifications.new": "Novo",
    "dept.notifications.settings": "Definições de Notificações",
    "dept.notifications.managePrefs":
      "Gira as suas preferências de notificações",
    "dept.notifications.email": "Notificações por Email",
    "dept.notifications.emailDesc": "Receba notificações por email",
    "dept.notifications.reminders": "Lembretes de Relatório",
    "dept.notifications.remindersDesc":
      "Receba lembretes sobre prazos de relatórios",
    "dept.notifications.system": "Atualizações do Sistema",
    "dept.notifications.systemDesc":
      "Receba notificações sobre manutenção e atualizações do sistema",
    // Department - Settings
    "dept.settings.title": "Definições",
    "dept.settings.subtitle": "Gira as definições e preferências da sua conta",
    "dept.settings.profile": "Definições de Perfil",
    "dept.settings.fullName": "Nome Completo",
    "dept.settings.hospital": "Hospital",
    "dept.settings.department": "Departamento",
    "dept.settings.notifications": "Definições de Notificações",
    "dept.settings.emailNotifications": "Notificações por Email",
    "dept.settings.reportReminders": "Lembretes de Relatório",
    "dept.settings.dataUpdates": "Atualizações de Dados",
    "dept.settings.dataUpdatesDesc":
      "Notificações quando os dados forem atualizados",
    "dept.settings.security": "Definições de Segurança",
    "dept.settings.currentPassword": "Palavra-passe Atual",
    "dept.settings.newPassword": "Nova Palavra-passe",
    "dept.settings.confirmPassword": "Confirmar Nova Palavra-passe",
    "dept.settings.system": "Definições do Sistema",
    "dept.settings.autoSaveDrafts": "Guardar Rascunhos Automaticamente",
    "dept.settings.autoSaveDraftsDesc":
      "Guardar automaticamente os dados do formulário como rascunhos",
    "dept.settings.dataExport": "Exportação de Dados",
    "dept.settings.dataExportDesc":
      "Permitir funcionalidade de exportação de dados",
    "dept.settings.analytics": "Analítica",
    "dept.settings.analyticsDesc":
      "Ativar funcionalidades de análise e relatórios",
    // Department - Help
    "dept.help.title": "Ajuda e Suporte",
    "dept.help.subtitle":
      "Obtenha ajuda para usar o dashboard de sustentabilidade",
    "dept.help.sendMessage": "Enviar Mensagem",
    "dept.help.firstName": "Primeiro Nome",
    "dept.help.lastName": "Apelido",
    "dept.help.phoneNumber": "Número de Telefone",
    "dept.help.message": "Mensagem",
    "dept.help.sending": "A enviar...",
    "dept.help.send": "Enviar Mensagem",
    "dept.help.contactInfo": "Informações de Contacto",
    "dept.help.phone": "Telefone",
    "dept.help.email": "Email",
    "dept.help.address": "Morada",
    "dept.help.directSupport": "Suporte Direto",
    "dept.help.chatWhatsApp": "Conversar no WhatsApp",
    "dept.help.chatWhatsAppDesc": "Envie mensagem à nossa equipa no WhatsApp",
    // Admin - Common/Sections
    "admin.common.loading": "A carregar...",
    "admin.common.loadingUsers": "A carregar utilizadores...",
    "admin.common.loadingDepartments":
      "A carregar responsáveis de departamento...",
    "admin.common.noDepartments": "Sem responsáveis de departamento",
    "admin.common.noForms": "Sem dados de formulários",
    "admin.common.notAssigned": "Não atribuído",
    "admin.common.na": "N/D",
    "admin.common.never": "Nunca",
    "admin.common.submitted": "Submetido",
    "admin.common.pending": "Pendente",
    "admin.dashboard.deptSectionTitle":
      "Responsáveis de Departamento - Estado de Submissão e Lembretes",
    "admin.dashboard.deptSectionHelp":
      "Atribua responsáveis aos hospitais na secção de Gestão de Utilizadores abaixo para ativar a funcionalidade de lembretes.",
    "admin.dashboard.sendReminder": "Enviar Lembrete",
    "admin.dashboard.sending": "A enviar...",
    "admin.dashboard.submitted": "Submetido",
    "admin.users.sectionTitle":
      "Gestão de Utilizadores - Atribuição de Hospital",
    "admin.users.loading": "A carregar utilizadores...",
    "admin.users.allAssigned":
      "Todos os utilizadores foram atribuídos a hospitais!",
    "admin.users.table.name": "Nome",
    "admin.users.table.email": "Email",
    "admin.users.table.role": "Função",
    "admin.users.table.created": "Criado",
    "admin.users.table.assignHospital": "Atribuir Hospital",
    "admin.forms.sectionTitle":
      "Submissões de Todos os Hospitais - Dados dos Formulários",
    "admin.forms.sectionDesc":
      'Veja todas as submissões de todos os hospitais. Clique em "Ver Relatório" para ver métricas detalhadas.',
    "admin.forms.loading": "A carregar dados dos formulários...",
    "admin.forms.error": "Erro ao carregar dados dos formulários",
    "admin.forms.totals": "Formulários Totais",
    "admin.forms.submitted": "Submetidos",
    "admin.forms.pending": "Pendentes",
    "admin.forms.refresh": "Atualizar",
    "admin.forms.table.hospital": "Hospital",
    "admin.forms.table.deptHead": "Responsável de Departamento",
    "admin.forms.table.monthYear": "Mês/Ano",
    "admin.forms.table.status": "Estado",
    "admin.forms.table.submittedAt": "Submetido Em",
    "admin.forms.table.created": "Criado",
    "admin.forms.table.actions": "Ações",
    "admin.forms.viewReport": "Ver Relatório",
    // Hospital Forms Management translations
    "admin.hospitalForms.title": "Gestão de Formulários do Hospital",
    "admin.hospitalForms.description":
      "Gerir e preencher formulários para todos os hospitais",
    "admin.hospitalForms.filters": "Filtros",
    "admin.hospitalForms.selectHospital": "Selecionar Hospital",
    "admin.hospitalForms.allHospitals": "Todos os Hospitais",
    "admin.hospitalForms.currentMonth": "Mês Atual",
    "admin.hospitalForms.currentYear": "Ano Atual",
    "admin.hospitalForms.refresh": "Atualizar",
    "admin.hospitalForms.hospitalForms": "Formulários do Hospital",
    "admin.hospitalForms.loading": "A carregar formulários...",
    "admin.hospitalForms.noForms":
      "Nenhum formulário encontrado para os critérios selecionados",
    "admin.hospitalForms.createNew": "Criar Novo Formulário",
    "admin.hospitalForms.hospital": "Hospital",
    "admin.hospitalForms.monthYear": "Mês/Ano",
    "admin.hospitalForms.status": "Estado",
    "admin.hospitalForms.submittedAt": "Submetido Em",
    "admin.hospitalForms.lastUpdated": "Última Atualização",
    "admin.hospitalForms.actions": "Ações",
    "admin.hospitalForms.view": "Ver",
    "admin.hospitalForms.edit": "Editar",
    "admin.hospitalForms.submitted": "Submetido",
    "admin.hospitalForms.pending": "Pendente",
    "admin.hospitalForms.notSubmitted": "Não submetido",
    "admin.hospitalForms.backToForms": "Voltar aos Formulários do Hospital",
    "admin.hospitalForms.viewMode":
      "Modo de Visualização: Este formulário foi submetido e é só de leitura",
    // Admin Dashboard - Cumulative Metrics
    "admin.dashboard.cumulativeMetrics":
      "Métricas Cumulativas - Indicadores Chave de Sustentabilidade",
    "admin.dashboard.cumulativeMetricsDesc":
      "Totais agregados de todos os hospitais para o mês atual",
    "admin.dashboard.electricityUsage": "Consumo de Eletricidade",
    "admin.dashboard.waterUsage": "Consumo de Água",
    "admin.dashboard.wasteType1": "Resíduos Tipo 1",
    "admin.dashboard.wasteType2": "Resíduos Tipo 2",
    "admin.dashboard.wasteType3": "Resíduos Tipo 3",
    "admin.dashboard.wasteType4": "Resíduos Tipo 4",
    "admin.dashboard.co2Emissions": "Emissões de CO₂",
    "admin.dashboard.kilometersTravelled": "Quilómetros Percorridos",
    "admin.dashboard.renewableEnergyCreated": "Energia Renovável Criada",
    "admin.dashboard.fuelTypeMix": "Mistura de Tipos de Combustível",
    "admin.dashboard.licensePlatesRecorded": "Matrículas Registadas",
    "admin.dashboard.vsLastMonth": "vs mês passado",
    "admin.dashboard.vehicleEntries":
      "Entradas de veículos categorizadas por tipo de combustível este mês",
    "admin.dashboard.totalEntriesWithPlates":
      "Total de entradas com números de matrícula este mês",
    // Admin Dashboard - CO2 Trend Analysis
    "admin.dashboard.co2TrendAnalysis": "Análise de Tendências de CO₂",
    "admin.dashboard.co2TrendDesc":
      "Tendências de emissões de CO₂ em todo o sistema em todos os hospitais",
    "admin.dashboard.totalEmissions": "Emissões Totais",
    "admin.dashboard.averagePerHospital": "Média por Hospital",
    "admin.dashboard.renewableEnergyRatio": "Rácio de Energia Renovável",
    "admin.dashboard.kgCO2e": "kg CO₂e",
    "admin.dashboard.avgPerHospital": "Média por Hospital",
    "admin.dashboard.renewableRatio": "Rácio Renovável",
    // Admin Dashboard - All Hospital Submissions
    "admin.dashboard.allSubmissions": "Todas as Submissões de Hospitais",
    "admin.dashboard.allSubmissionsDesc":
      "Visão geral de todas as submissões de todos os hospitais",
    "admin.dashboard.loadingMetrics": "A carregar métricas...",
    "admin.dashboard.noData": "Sem dados",
    "admin.dashboard.hospital": "Hospital",
    "admin.dashboard.departmentHead": "Responsável de Departamento",
    "admin.dashboard.submissionStatus": "Estado de Submissão",
    "admin.dashboard.lastUpdated": "Última Atualização",
    "admin.dashboard.viewReport": "Ver Relatório",
    "admin.dashboard.assignHospital": "Atribuir Hospital",
    "admin.dashboard.assigning": "A atribuir...",
    "admin.dashboard.selectHospital": "Selecionar Hospital",
    "admin.dashboard.assign": "Atribuir",
    "admin.dashboard.assignmentSuccess": "Hospital atribuído com sucesso!",
    "admin.dashboard.assignmentError": "Erro ao atribuir hospital",
    // Admin Data Analysis
    "admin.dataAnalysis.title": "Análise de Dados",
    "admin.dataAnalysis.subtitle":
      "Análise detalhada dos dados de sustentabilidade",
    "admin.dataAnalysis.selectMetric": "Selecionar Métrica",
    "admin.dataAnalysis.selectHospital": "Selecionar Hospital",
    "admin.dataAnalysis.loading": "A carregar dados...",
    "admin.dataAnalysis.noData": "Sem dados disponíveis",
    "admin.dataAnalysis.monthlyTrend": "Tendência Mensal",
    "admin.dataAnalysis.hospitalComparison": "Comparação de Hospitais",
    "admin.dataAnalysis.electricity": "Eletricidade",
    "admin.dataAnalysis.water": "Água",
    "admin.dataAnalysis.waste": "Resíduos",
    "admin.dataAnalysis.co2": "CO₂",
    "admin.dataAnalysis.kilometers": "Quilómetros",
    "admin.dataAnalysis.renewableEnergy": "Energia Renovável",
    // Admin Notifications
    "admin.notifications.title": "Notificações",
    "admin.notifications.subtitle": "Gerir notificações do sistema",
    "admin.notifications.loading": "A carregar notificações...",
    "admin.notifications.noNotifications": "Sem notificações",
    "admin.notifications.markAllRead": "Marcar todas como lidas",
    "admin.notifications.markAsRead": "Marcar como lida",
    "admin.notifications.delete": "Eliminar",
    "admin.notifications.unread": "por ler",
    "admin.notifications.read": "lida",
    "admin.notifications.sent": "enviada",
    "admin.notifications.pending": "pendente",
    // Admin Support Messages
    "admin.supportMessages.title": "Mensagens de Suporte",
    "admin.supportMessages.subtitle":
      "Gerir mensagens de suporte dos utilizadores",
    "admin.supportMessages.loading": "A carregar mensagens...",
    "admin.supportMessages.noMessages": "Sem mensagens",
    "admin.supportMessages.reply": "Responder",
    "admin.supportMessages.markAsResolved": "Marcar como Resolvido",
    "admin.supportMessages.resolved": "Resolvido",
    "admin.supportMessages.pending": "Pendente",
    "admin.supportMessages.from": "De",
    "admin.supportMessages.subject": "Assunto",
    "admin.supportMessages.message": "Mensagem",
    "admin.supportMessages.status": "Estado",
    "admin.supportMessages.date": "Data",
    // FAQ
    "faq.title": "FAQ",
    "faq.subtitle":
      "Encontre respostas para perguntas comuns sobre o sistema de dados de sustentabilidade.",
    "faq.searchPlaceholder": "Buscar FAQ...",
    "faq.categories.dataEntry": "Entrada de Dados",
    "faq.categories.deadlines": "Prazos",
    "faq.categories.language": "Idioma",
    "faq.categories.support": "Suporte",
    "faq.categories.analytics": "Análises",
    // New sustainability metrics translations
    "metrics.kilometersTravelled": "Quilómetros Percorridos",
    "metrics.kilometersByFuel": "Quilómetros por Combustível",
    "metrics.renewableEnergyCreated": "Energia Renovável Criada",
    "metrics.licensePlatesRecorded": "Matrículas Registadas",
    "metrics.totalKilometers": "Total de Quilómetros",
    "metrics.gasKilometers": "Quilómetros a Gás",
    "metrics.dieselKilometers": "Quilómetros a Diesel",
    "metrics.gasolineKilometers": "Quilómetros a Gasolina",
    "metrics.energyUsage": "Consumo de Energia",
    "metrics.waterUsage": "Consumo de Água",
    "metrics.wasteGenerated": "Resíduos Gerados",
    "metrics.co2Emissions": "Emissões de CO₂",
    "metrics.renewableEnergyRatio": "Rácio de Energia Renovável",
    "metrics.renewableVsTotal": "Energia Renovável vs Total",
    "metrics.licensePlateNumber": "Número da Matrícula",
    "metrics.vehicleIdentifier": "Identificador da matrícula do veículo",
    "metrics.kilometersGas": "Quilómetros percorridos por veículos a gás",
    "metrics.kilometersDiesel": "Quilómetros percorridos por veículos a diesel",
    "metrics.kilometersGasoline":
      "Quilómetros percorridos por veículos a gasolina",
    "metrics.renewableEnergyOnSite":
      "Quantidade de energia renovável gerada no local",
    "metrics.sumAcrossDepartments": "Soma em todos os departamentos este mês",
    "metrics.totalEntriesWithPlates":
      "Total de entradas com números de matrícula este mês",
    "metrics.energyTrend": "Tendência de Energia",
    "metrics.energyTrendDesc":
      "Consumo de energia do seu hospital no último ano",
    "metrics.energyEfficiency": "Eficiência Energética",
    "metrics.energy": "Energia",
    "metrics.energyUsageData": "Dados de Consumo de Energia",
    "metrics.energyTrendTitle": "Tendência de Energia de 12 Meses",
    "metrics.energyTrendDescription":
      "Consumo de energia do seu hospital no último ano",
    "metrics.energyUsageKwh": "Consumo de Energia (kWh)",
    "metrics.waterUsageM3": "Consumo de Água (m³)",
    "metrics.wasteType1": "Resíduos Tipo 1 (kg)",
    "metrics.wasteType2": "Resíduos Tipo 2 (kg)",
    "metrics.wasteType3": "Resíduos Tipo 3 (kg)",
    "metrics.wasteType4": "Resíduos Tipo 4 (kg)",
    "metrics.co2EmissionsKg": "Emissões de CO₂ (kg CO₂e)",
    "metrics.kilometersGasKm": "Quilómetros (Gás) (km)",
    "metrics.litersGasConsumed": "Litros Consumidos (Gás)",
    "metrics.litersGasUsed": "Litros de gás consumidos por veículos",
    "metrics.kilometersDieselKm": "Quilómetros (Diesel) (km)",
    "metrics.litersDieselConsumed": "Litros Consumidos (Diesel)",
    "metrics.litersDieselUsed": "Litros de diesel consumidos por veículos",
    "metrics.kilometersGasolineKm": "Quilómetros (Gasolina) (km)",
    "metrics.litersGasolineConsumed": "Litros Consumidos (Gasolina)",
    "metrics.litersGasolineUsed": "Litros de gasolina consumidos por veículos",
    "metrics.licensePlate": "Matrícula",
    "metrics.renewableEnergyCreatedKwh": "Energia Renovável Criada (kWh)",
  },
};

export function useLanguage(): LanguageContextType {
  const [language, setLanguage] = useState<Language>("en");

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language;
    if (savedLanguage && (savedLanguage === "en" || savedLanguage === "pt")) {
      setLanguage(savedLanguage);
    }
  }, []);

  // Save language to localStorage when changed
  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const t = (key: string): string => {
    return (
      translations[language][key as keyof (typeof translations)["en"]] || key
    );
  };

  const toggleLanguage = () => {
    setLanguage(language === "en" ? "pt" : "en");
  };

  return {
    language,
    setLanguage,
    toggleLanguage,
    t,
  };
}
